### ISSUE TITLE
TypeError: can't access property "stable_ping_table_names"

### ISSUE THREAD

**Issue by robhudson** [mozilla/glean-dictionary#320] opened 2021-01-14 18:55 UTC
e.g. https://glean-dictionary.protosaur.dev/apps/firefox-ios-beta/metrics/tabs-new_tab_pressed

**Comment by Iinh** [comment] 2021-01-14 19:49
I'm wondering if this might be because of the recent changes in `probe-scraper`... https://github.com/mozilla/probe-scraper/pull/262.

**Comment by Iinh** [comment] 2021-01-14 20:16
I was not able to reproduce this problem locally. Maybe @wlach has more insights into this?

**Comment by wlach** [comment] 2021-01-14 20:22
I think this is due to a mismatch between the data and the site, what's on protosaur right now is just a dev copy I created on my workstation. I'll do up a quick fix now (since I announced the URL on Slack) and hopefully address #60 tomorrow.

**Comment by wlach** [comment] 2021-01-14 22:02
Fixed now

**Closed by wlach** 2021-01-14 22:02 UTC
