### ISSUE TITLE
Attempting to add an annotation for new metrics leads to a GitHub 404

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/glean-dictionary#1110] opened 2022-01-31 14:59 UTC
When browsing to the metrics, if the metric does not have any previous annotation, the following UI is showed:

![immagine](https://user-images.githubusercontent.com/883721/151815823-81669b50-09d2-4b3f-b6f5-615355779690.png)

Clicking on the "add some" link leads to a 404 page on GitHub. That's because, I believe, the link is, for example, like follows:

`https://github.com/mozilla/glean-annotations/`**`edit`**`/main/annotations/fenix/metrics/activation.activation_id/README.md`

Note the `edit` action. One way to mitigate this would be to use a different URL if no previous annotation could be found, for example:

`https://github.com/mozilla/glean-annotations/new/main/?filename=annotations/fenix/metrics/activation.activation_id/README.md&value=Type%20your%20annotation%20here`

**Comment by wlach** [comment] 2022-02-01 17:25
This definitely used to work. Not sure what happened

**Comment by Iinh** [comment] 2022-02-03 19:51
I'm not sure what happened either (I was not able to reproduce the issue). For example, clicking on the "add some" link for this probe seems to work ok: https://dictionary.telemetry.mozilla.org/apps/fenix/metrics/activation_activation_id

I'm closing this issue for now, feel free to reopen it if I missed anything @Dexterp37.

**Closed by Iinh** 2022-02-03 19:51 UTC

**Comment by Dexterp37** [comment] 2022-02-03 20:25
Weird, it works :| Thanks for double checking, it definitely wasn't working before and was leading me to a 404. Caching? No clue.

**Comment by wlach** [comment] 2022-02-03 22:14
> Weird, it works :| Thanks for double checking, it definitely wasn't working before and was leading me to a 404. Caching? No clue.

May have been a GitHub bug?
